import {
	createAppointment,
	deleteAppointment,
	getAppointment,
	listAppointments,
	updateAppointment,
	updateAppointmentStatus,
} from "./appointments";
import {
	createBankAccount,
	deleteBankAccount,
	listBankAccounts,
	setDefaultBankAccount,
	updateBankAccount,
} from "./bank-accounts";
import {
	createBranch,
	deleteBranch,
	listBranches,
	listUserBranches,
	updateBranch,
	validateBranch,
} from "./branches";
import { getAuditLogForUser, getGlobalAuditLog } from "./cdc";
import { getCompany, updateCompany } from "./companies";
import {
	checkDoctorIdUniqueness,
	checkEmailUniqueness,
	checkRegistrationNumberUniqueness,
	createDoctor,
	createDoctorDocument,
	createIpdSchedule,
	createOpdSchedule,
	createUnavailability,
	deleteDoctor,
	deleteDoctorDocument,
	deleteIpdSchedule,
	deleteOpdSchedule,
	deleteUnavailability,
	getAvailableSlots,
	getDoctor,
	getPresignedDoctorDocumentUrl,
	getPresignedDoctorPhotoUrl,
	listDoctorDocuments,
	listDoctors,
	listIpdAvailability,
	listOpdAvailability,
	listUnavailability,
	updateDoctor,
	updateDoctorSpecializations,
	updateIpdSchedule,
	updateOpdSchedule,
} from "./doctors";
import {
	createDraft,
	deleteDraft,
	getDraft,
	listDrafts,
	updateDraft,
} from "./drafts";
import {
	createCategory,
	createFacility,
	createFacilitySchedule,
	deleteCategory,
	deleteFacility,
	deleteFacilitySchedule,
	getCategory,
	getFacility,
	listCategories,
	listFacilities,
	listFacilitySchedules,
	updateCategory,
	updateFacility,
	updateFacilitySchedule,
} from "./facilities";
import { deleteFile, getPresignedFileUploadUrl } from "./files";
import {
	createPatient,
	deletePatient,
	getPatient,
	getPresignedPatientPhotoUrl,
	listPatients,
	updatePatient,
} from "./patients";
import {
	createService,
	deleteService,
	getService,
	listServices,
	updateService,
} from "./services";
import {
	createSpecialization,
	deleteSpecialization,
	getSpecialization,
	listSpecializations,
	updateSpecialization,
} from "./specializations";
import {
	createStaff,
	deleteStaff,
	getPresignedStaffPhotoUrl,
	getStaff,
	getStaffOrgChart,
	listBranchesForCompany,
	listCompanies,
	listStaff,
	listStaffPermissions,
	updateStaff,
	updateStaffPermissions,
} from "./staff";
import {
	createVendor,
	deleteVendor,
	getVendor,
	listVendors,
	updateVendor,
} from "./vendors";

export default {
	appointments: {
		create: createAppointment,
		delete: deleteAppointment,
		get: getAppointment,
		list: listAppointments,
		update: updateAppointment,
		updateStatus: updateAppointmentStatus,
	},
	bankAccounts: {
		create: createBankAccount,
		delete: deleteBankAccount,
		list: listBankAccounts,
		setDefault: setDefaultBankAccount,
		update: updateBankAccount,
	},
	branches: {
		create: createBranch,
		delete: deleteBranch,
		list: listBranches,
		listForCompany: listBranchesForCompany,
		listUser: listUserBranches,
		update: updateBranch,
		validate: validateBranch,
	},
	cdc: {
		getAuditLogForUser,
		getGlobalAuditLog,
	},
	companies: {
		get: getCompany,
		list: listCompanies,
		update: updateCompany,
	},
	doctors: {
		availableSlots: {
			get: getAvailableSlots,
		},
		checkDoctorIdUniqueness,
		checkEmailUniqueness,
		checkRegistrationNumberUniqueness,
		create: createDoctor,
		delete: deleteDoctor,
		documents: {
			create: createDoctorDocument,
			delete: deleteDoctorDocument,
			getPresignedUrl: getPresignedDoctorDocumentUrl,
			list: listDoctorDocuments,
		},
		get: getDoctor,
		getPresignedPhotoUrl: getPresignedDoctorPhotoUrl,
		ipdSchedules: {
			create: createIpdSchedule,
			delete: deleteIpdSchedule,
			list: listIpdAvailability,
			update: updateIpdSchedule,
		},
		list: listDoctors,
		opdSchedules: {
			create: createOpdSchedule,
			delete: deleteOpdSchedule,
			list: listOpdAvailability,
			update: updateOpdSchedule,
		},
		unavailability: {
			create: createUnavailability,
			delete: deleteUnavailability,
			list: listUnavailability,
		},
		update: updateDoctor,
		updateSpecializations: updateDoctorSpecializations,
	},
	drafts: {
		create: createDraft,
		delete: deleteDraft,
		get: getDraft,
		list: listDrafts,
		update: updateDraft,
	},
	facilities: {
		categories: {
			create: createCategory,
			delete: deleteCategory,
			get: getCategory,
			list: listCategories,
			update: updateCategory,
		},
		create: createFacility,
		delete: deleteFacility,
		get: getFacility,
		list: listFacilities,
		schedules: {
			create: createFacilitySchedule,
			delete: deleteFacilitySchedule,
			list: listFacilitySchedules,
			update: updateFacilitySchedule,
		},
		update: updateFacility,
	},
	files: {
		delete: deleteFile,
		getPresignedUploadUrl: getPresignedFileUploadUrl,
	},
	patients: {
		create: createPatient,
		delete: deletePatient,
		get: getPatient,
		getPresignedPhotoUrl: getPresignedPatientPhotoUrl,
		list: listPatients,
		update: updatePatient,
	},
	services: {
		create: createService,
		delete: deleteService,
		get: getService,
		list: listServices,
		update: updateService,
	},
	specializations: {
		create: createSpecialization,
		delete: deleteSpecialization,
		get: getSpecialization,
		list: listSpecializations,
		update: updateSpecialization,
	},
	staff: {
		create: createStaff,
		delete: deleteStaff,
		get: getStaff,
		getOrgChart: getStaffOrgChart,
		getPresignedPhotoUrl: getPresignedStaffPhotoUrl,
		list: listStaff,
		listPermissions: listStaffPermissions,
		update: updateStaff,
		updatePermissions: updateStaffPermissions,
	},
	vendors: {
		create: createVendor,
		delete: deleteVendor,
		get: getVendor,
		list: listVendors,
		update: updateVendor,
	},
};
