telemetry=false
logLevel="warn"

[console]
depth=10

[run]
bun=true
silent=false

[install]
minimumReleaseAge=259200 # 3 days
saveTextLockfile=false
ignore-scripts=true

# [test]
# coverage = true
# coverageThreshold = 0.8
# coverageSkipTestFiles = true
# coverageReporter = ["text", "lcov"]
# coverageDir = "coverage"
# pathIgnorePatterns = [
#   "node_modules/**",
#   "dist/**",
#   "build/**",
#   ".next/**",
#   "coverage/**",
#   "fixtures/**"
# ]
# randomize = true
# onlyFailures = true

# [test.reporter]
# junit = "test-results.xml"
