import {
	logs as adminLogs,
	createBranch,
	createRole,
	deleteRole,
	deleteTemplate,
	disableUser,
	getCompany,
	listBranches,
	listCptCodes,
	listMasterVersions,
	listRecallRules,
	listRoles,
	listTemplates,
	saveCompany,
	saveCptVersion,
	saveMasterVersion,
	saveRecallRule,
	saveTemplate,
	updateBranch,
	upsertCptCode,
} from "./procedures/admin";
import {
	registerEntry as allopathyRegisterEntry,
	checkInteraction as checkAllopathyInteraction,
	problemList as listAllopathyProblems,
	listSoap,
	logChronic,
	recordImmunization,
	saveExam as saveAllopathyExam,
	saveSoap,
	triageEntry,
	problemUpsert as upsertAllopathyProblem,
} from "./procedures/allopathy";
import {
	book as bookAppointment,
	bookVideo as bookVideoAppointment,
	callNext as callNextToken,
	cancel as cancelAppointment,
	captureConsent as captureVideoConsent,
	checkin as checkinAppointment,
	computeSlots,
	get as getAppointment,
	issueCertificate,
	issueRecall,
	list as listAppointments,
	markNoShow as markAppointmentNoShow,
	queueBoard,
	reschedule as rescheduleAppointment,
	walkinToken,
} from "./procedures/appointments";
import { getSession } from "./procedures/auth";
import {
	bookNadi,
	createYogaBatch,
	dualCode as dualCodeAyush,
	enrollYoga,
	issueDiet,
	listFollowUpGrid as listAyushFollowUpGrid,
	markYogaAttendance as markAyushYogaAttendance,
	pauseExtendPackage as pauseExtendAyushPackage,
	prescribeAyush,
	recordPackageOutcome as recordAyushPackageOutcome,
	recordSitting as recordAyushSitting,
	repertorize,
	saveFollowUpGrid as saveAyushFollowUpGrid,
	saveCaseSheet,
	scheduleTherapy,
	sellPackage as sellAyushPackage,
} from "./procedures/ayush";
import {
	applyDiscount as applyBillingDiscount,
	cndnIssue as billingCndnIssue,
	collect as collectBilling,
	collectionReport,
	duesAging,
	getInvoice,
	gstExport,
	interimTab,
	invoiceFinalize,
	invoiceRaise,
	packageExpireRun,
	packageLiability,
	packageRedeem,
	packageSell,
	pricelistUpsert,
	repriceOnPayerSwitch,
	settleAdvance,
	settle as settleBilling,
} from "./procedures/billing";
import {
	bookChair,
	buildPlan as buildDentalPlan,
	chart as chartDental,
	closeStage as closeDentalStage,
	consent as dentalConsent,
	implantMilestone as dentalImplantMilestone,
	quote as dentalQuote,
	pendingJobs as pendingDentalJobs,
	raiseLabJob,
	rescheduleStage as rescheduleDentalStage,
	sellPackage as sellDentalPackage,
	trackLabJob,
} from "./procedures/dental";
import {
	addonTest,
	authorize as authorizeLab,
	cancelOrder as cancelDiagnosticOrder,
	collectSample,
	criticalAck,
	deliver as deliverLab,
	queue as diagnosticsQueue,
	getOrder as getDiagnosticOrder,
	orderLabs,
	panelCreate,
	processingStart,
	qcLog,
	radioAuthorize,
	radioBook,
	radioCheckin,
	radioReportAttach,
	radioReschedule,
	receiveSample,
	resultEnter,
	sampleReject,
	tatReport,
	testMasterUpsert,
} from "./procedures/diagnostics";
import {
	addendum as addEncounterAddendum,
	addDiagnosis as addEncounterDiagnosis,
	create as createEncounter,
	get as getEncounter,
	placeOrder as placeEncounterOrder,
	prescribe as prescribeEncounter,
	recordVitals as recordEncounterVitals,
	refill as refillEncounter,
	setFollowUp as setEncounterFollowUp,
	sign as signEncounter,
} from "./procedures/encounters";
import {
	addBlock as addFacilityBlock,
	create as createFacility,
	overlap as facilityOverlap,
	statusBoard as facilityStatusBoard,
	get as getFacility,
	list as listFacilities,
	logSterilization,
	occupy as occupyFacility,
	release as releaseFacility,
	setSchedule as setFacilitySchedule,
	update as updateFacility,
} from "./procedures/facilities";
import {
	drugAdminister as administerNursingDrug,
	ioChart as chartNursingIo,
	vitalsChart as chartNursingVitals,
	handoverCompile as compileNursingHandover,
	missedEscalate as escalateNursingMissed,
	board as nursingBoard,
	checklistRecord as recordNursingChecklist,
	painScore as scoreNursingPain,
	riskScreen as screenNursingRisk,
	handoverSign as signNursingHandover,
	sittingsSupport as supportNursingSitting,
	triageTag as tagNursingTriage,
	tasksFromOrders as tasksFromNursingOrders,
} from "./procedures/nursing";
import {
	attendanceMark,
	auditQuery,
	branchesCreate,
	complianceEvidence,
	complianceList,
	explorerExportCsv,
	explorerGrant,
	explorerQuery,
	hrStaffUpsert,
	leaveDecide,
	leaveRequest,
	mastersGet,
	mastersUpsert,
	messagingOptOut,
	messagingRetry,
	messagingSend,
	payrollExport,
	reportsDefine,
	reportsList,
	reportsRun,
	rosterPlan,
	seedPresets,
} from "./procedures/operations";
import {
	getCurrentOrganization,
	getOrganizationBySubdomain,
	listMyOrganizations,
	listOrganizations,
	updateCurrentOrganization,
} from "./procedures/organizations";
import {
	addAllergy,
	approveMerge,
	archiveConsent,
	dedupeCheck,
	enrolRecall,
	get as getPatient,
	linkFamily,
	list as listPatients,
	logCommunication,
	timeline as patientTimeline,
	register as registerPatient,
	requestMerge,
	setFlag,
	shareSlip,
} from "./procedures/patients";
import {
	transferAccept as acceptStockTransfer,
	batchReceive,
	expiryAlerts,
	getSale,
	grnVerify,
	itemUpsert,
	partialClose as partialCloseSale,
	cndnIssue as pharmacyCndnIssue,
	piBook,
	poCreate,
	reorderSuggest,
	returnAgainstBill,
	saleFromRx,
	stockCorrect,
	stockLedger,
	transfer as transferStock,
} from "./procedures/pharmacy";
import {
	addEducation,
	addPosting,
	addRegistration,
	blockLeave,
	create as createPractitioner,
	deactivate as deactivatePractitioner,
	get as getPractitioner,
	list as listPractitioners,
	nextFreeSlot,
	conflict as practitionerConflict,
	setFee,
	setSchedule as setPractitionerSchedule,
	update as updatePractitioner,
} from "./procedures/practitioners";
import {
	alertSenior as alertPsychSenior,
	assess as assessPsych,
	bookCounselling,
	bookTele as bookPsychTele,
	caregiverConsent,
	chartWithdrawal,
	closeReadiness as closePsychReadiness,
	involuntaryHook,
	prescribeControlled,
	breakGlass as psychBreakGlass,
	recallList as psychRecallList,
	relapsePlan,
	saveSafetyPlan,
	scoreScale as scorePsychScale,
	screenRisk as screenPsychRisk,
	sideEffectCheck,
} from "./procedures/psych";
import {
	addendumAppend as appendRecordAddendum,
	registersAppend as appendRecordRegister,
	docsAttach as attachRecordDocs,
	retentionCheck as checkRecordRetention,
	registersExport as exportRecordRegisters,
	consentsGet as getRecordConsents,
	encounterGet as getRecordEncounter,
	dischargeIssue as issueRecordDischarge,
	notesMask as maskRecordNotes,
	merge as mergeRecords,
	familySummaryMulti as multiResidentFamilySummary,
	dischargePending as pendingRecordDischarges,
	recordConsent as recordRecordConsent,
	breakglass as recordsBreakglass,
	familySummary as recordsFamilySummary,
	recentlyUsedRx as recordsRecentlyUsedRx,
	timeline as recordsTimeline,
	search as searchRecords,
	sharePrint as shareRecordPrint,
	shareWhatsapp as shareRecordWhatsapp,
	docsVerify as verifyRecordDocs,
	registersVoid as voidRecordRegister,
} from "./procedures/records";
import {
	assess as assessRehab,
	bookSitting as bookRehabSitting,
	buildPackage as buildRehabPackage,
	discharge as dischargeRehab,
	exerciseSheet,
	openEpisode as openRehabEpisode,
	recordSitting as recordRehabSitting,
	dayBoard as rehabDayBoard,
	progressChart as rehabProgressChart,
	rescore as rescoreRehab,
	setGoals as setRehabGoals,
	shareExerciseSheet as shareRehabExerciseSheet,
} from "./procedures/rehab";
import {
	admit as admitResident,
	allocateBed as allocateResidentBed,
	visitLog as appendResidentVisitLog,
	compileStayBill,
	feedback as feedbackResident,
	getResident,
	listResidents,
	logDaily as logResidentDaily,
	polypharmacyReview,
	raiseAlert as raiseResidentAlert,
	recordStayCharge as recordResidentStayCharge,
	familySummary as residentFamilySummary,
	round as residentRound,
	scoreGeriatric,
	sendFamilySummary as sendResidentFamilySummary,
} from "./procedures/residents";
import {
	createServiceProvider,
	listServiceProviders,
} from "./procedures/service-providers";
import {
	addDiscountRule,
	create as createService,
	definePackage,
	get as getService,
	list as listServices,
	mapFacilities as mapServiceFacilities,
	publish as publishService,
	redeem as redeemPackage,
	retire as retireService,
	setPrice as setServicePrice,
	update as updateService,
} from "./procedures/services";
import { listTenants, onboardTenant } from "./procedures/tenants";
import {
	createUser,
	getUser,
	listUsers,
	removeUser,
	updateUser,
} from "./procedures/users";

export const router = {
	admin: {
		createBranch,
		createRole,
		deleteRole,
		deleteTemplate,
		disableUser,
		getCompany,
		listBranches,
		listCptCodes,
		listMasterVersions,
		listRecallRules,
		listRoles,
		listTemplates,
		logs: adminLogs,
		saveCompany,
		saveCptVersion,
		saveMasterVersion,
		saveRecallRule,
		saveTemplate,
		updateBranch,
		upsertCptCode,
	},
	allopathy: {
		checkInteraction: checkAllopathyInteraction,
		listSoap,
		logChronic,
		problemList: listAllopathyProblems,
		problemUpsert: upsertAllopathyProblem,
		recordImmunization,
		registerEntry: allopathyRegisterEntry,
		saveExam: saveAllopathyExam,
		saveSoap,
		triageEntry,
	},
	appointments: {
		book: bookAppointment,
		bookVideo: bookVideoAppointment,
		callNext: callNextToken,
		cancel: cancelAppointment,
		captureConsent: captureVideoConsent,
		checkin: checkinAppointment,
		computeSlots,
		get: getAppointment,
		issueCertificate,
		issueRecall,
		list: listAppointments,
		markNoShow: markAppointmentNoShow,
		queueBoard,
		reschedule: rescheduleAppointment,
		walkinToken,
	},
	auth: {
		getSession,
	},
	ayush: {
		bookNadi,
		createYogaBatch,
		dualCode: dualCodeAyush,
		enrollYoga,
		issueDiet,
		listFollowUpGrid: listAyushFollowUpGrid,
		markYogaAttendance: markAyushYogaAttendance,
		pauseExtendPackage: pauseExtendAyushPackage,
		prescribe: prescribeAyush,
		recordPackageOutcome: recordAyushPackageOutcome,
		recordSitting: recordAyushSitting,
		repertorize,
		saveCaseSheet,
		saveFollowUpGrid: saveAyushFollowUpGrid,
		scheduleTherapy,
		sellPackage: sellAyushPackage,
	},
	billing: {
		applyDiscount: applyBillingDiscount,
		cndnIssue: billingCndnIssue,
		collect: collectBilling,
		collectionReport,
		duesAging,
		getInvoice,
		gstExport,
		interimTab,
		invoiceFinalize,
		invoiceRaise,
		packageExpireRun,
		packageLiability,
		packageRedeem,
		packageSell,
		pricelistUpsert,
		repriceOnPayerSwitch,
		settle: settleBilling,
		settleAdvance,
	},
	dental: {
		bookChair,
		buildPlan: buildDentalPlan,
		chart: chartDental,
		closeStage: closeDentalStage,
		consent: dentalConsent,
		implantMilestone: dentalImplantMilestone,
		pendingJobs: pendingDentalJobs,
		quote: dentalQuote,
		raiseLabJob,
		rescheduleStage: rescheduleDentalStage,
		sellPackage: sellDentalPackage,
		trackLabJob,
	},
	diagnostics: {
		addonTest,
		authorize: authorizeLab,
		cancelOrder: cancelDiagnosticOrder,
		collectSample,
		criticalAck,
		deliver: deliverLab,
		getOrder: getDiagnosticOrder,
		orderLabs,
		panelCreate,
		processingStart,
		qcLog,
		queue: diagnosticsQueue,
		radioAuthorize,
		radioBook,
		radioCheckin,
		radioReportAttach,
		radioReschedule,
		receiveSample,
		resultEnter,
		sampleReject,
		tatReport,
		testMasterUpsert,
	},
	encounters: {
		addDiagnosis: addEncounterDiagnosis,
		addendum: addEncounterAddendum,
		create: createEncounter,
		get: getEncounter,
		placeOrder: placeEncounterOrder,
		prescribe: prescribeEncounter,
		recordVitals: recordEncounterVitals,
		refill: refillEncounter,
		setFollowUp: setEncounterFollowUp,
		sign: signEncounter,
	},
	facilities: {
		addBlock: addFacilityBlock,
		create: createFacility,
		get: getFacility,
		list: listFacilities,
		logSterilization,
		occupy: occupyFacility,
		overlap: facilityOverlap,
		release: releaseFacility,
		setSchedule: setFacilitySchedule,
		statusBoard: facilityStatusBoard,
		update: updateFacility,
	},
	nursing: {
		board: nursingBoard,
		checklistRecord: recordNursingChecklist,
		drugAdminister: administerNursingDrug,
		handoverCompile: compileNursingHandover,
		handoverSign: signNursingHandover,
		ioChart: chartNursingIo,
		missedEscalate: escalateNursingMissed,
		painScore: scoreNursingPain,
		riskScreen: screenNursingRisk,
		sittingsSupport: supportNursingSitting,
		tasksFromOrders: tasksFromNursingOrders,
		triageTag: tagNursingTriage,
		vitalsChart: chartNursingVitals,
	},
	operations: {
		attendanceMark,
		auditQuery,
		branchesCreate,
		complianceEvidence,
		complianceList,
		explorerExportCsv,
		explorerGrant,
		explorerQuery,
		hrStaffUpsert,
		leaveDecide,
		leaveRequest,
		mastersGet,
		mastersUpsert,
		messagingOptOut,
		messagingRetry,
		messagingSend,
		payrollExport,
		reportsDefine,
		reportsList,
		reportsRun,
		rosterPlan,
		seedPresets,
	},
	organizations: {
		bySubdomain: getOrganizationBySubdomain,
		current: getCurrentOrganization,
		list: listOrganizations,
		listMine: listMyOrganizations,
		update: updateCurrentOrganization,
	},
	patients: {
		addAllergy,
		approveMerge,
		archiveConsent,
		dedupeCheck,
		enrolRecall,
		get: getPatient,
		linkFamily,
		list: listPatients,
		logCommunication,
		register: registerPatient,
		requestMerge,
		setFlag,
		shareSlip,
		timeline: patientTimeline,
	},
	pharmacy: {
		batchReceive,
		cndnIssue: pharmacyCndnIssue,
		expiryAlerts,
		getSale,
		grnVerify,
		itemUpsert,
		partialClose: partialCloseSale,
		piBook,
		poCreate,
		reorderSuggest,
		returnAgainstBill,
		saleFromRx,
		stockCorrect,
		stockLedger,
		transfer: transferStock,
		transferAccept: acceptStockTransfer,
	},
	practitioners: {
		addEducation,
		addPosting,
		addRegistration,
		blockLeave,
		conflict: practitionerConflict,
		create: createPractitioner,
		deactivate: deactivatePractitioner,
		get: getPractitioner,
		list: listPractitioners,
		nextFreeSlot,
		setFee,
		setSchedule: setPractitionerSchedule,
		update: updatePractitioner,
	},
	psych: {
		alertSenior: alertPsychSenior,
		assess: assessPsych,
		bookCounselling,
		bookTele: bookPsychTele,
		breakGlass: psychBreakGlass,
		caregiverConsent,
		chartWithdrawal,
		closeReadiness: closePsychReadiness,
		involuntaryHook,
		prescribeControlled,
		recallList: psychRecallList,
		relapsePlan,
		saveSafetyPlan,
		scoreScale: scorePsychScale,
		screenRisk: screenPsychRisk,
		sideEffectCheck,
	},
	records: {
		addendumAppend: appendRecordAddendum,
		breakglass: recordsBreakglass,
		consentsGet: getRecordConsents,
		dischargeIssue: issueRecordDischarge,
		dischargePending: pendingRecordDischarges,
		docsAttach: attachRecordDocs,
		docsVerify: verifyRecordDocs,
		encounterGet: getRecordEncounter,
		familySummary: recordsFamilySummary,
		familySummaryMulti: multiResidentFamilySummary,
		merge: mergeRecords,
		notesMask: maskRecordNotes,
		recentlyUsedRx: recordsRecentlyUsedRx,
		recordConsent: recordRecordConsent,
		registersAppend: appendRecordRegister,
		registersExport: exportRecordRegisters,
		registersVoid: voidRecordRegister,
		retentionCheck: checkRecordRetention,
		search: searchRecords,
		sharePrint: shareRecordPrint,
		shareWhatsapp: shareRecordWhatsapp,
		timeline: recordsTimeline,
	},
	rehab: {
		assess: assessRehab,
		bookSitting: bookRehabSitting,
		buildPackage: buildRehabPackage,
		dayBoard: rehabDayBoard,
		discharge: dischargeRehab,
		exerciseSheet,
		openEpisode: openRehabEpisode,
		progressChart: rehabProgressChart,
		recordSitting: recordRehabSitting,
		rescore: rescoreRehab,
		setGoals: setRehabGoals,
		shareExerciseSheet: shareRehabExerciseSheet,
	},
	residents: {
		admit: admitResident,
		allocateBed: allocateResidentBed,
		compileStayBill,
		familySummary: residentFamilySummary,
		feedback: feedbackResident,
		getResident,
		listResidents,
		logDaily: logResidentDaily,
		polypharmacyReview,
		raiseAlert: raiseResidentAlert,
		recordStayCharge: recordResidentStayCharge,
		round: residentRound,
		scoreGeriatric,
		sendFamilySummary: sendResidentFamilySummary,
		visitLog: appendResidentVisitLog,
	},
	serviceProviders: {
		create: createServiceProvider,
		list: listServiceProviders,
	},
	services: {
		addDiscountRule,
		create: createService,
		definePackage,
		get: getService,
		list: listServices,
		mapFacilities: mapServiceFacilities,
		publish: publishService,
		redeem: redeemPackage,
		retire: retireService,
		setPrice: setServicePrice,
		update: updateService,
	},
	tenants: {
		list: listTenants,
		onboard: onboardTenant,
	},
	users: {
		create: createUser,
		get: getUser,
		list: listUsers,
		remove: removeUser,
		update: updateUser,
	},
};
