import {
	logs as adminLogs,
	createBranch,
	createRole,
	deleteRole,
	deleteTemplate,
	disableUser,
	getCompany,
	listBranches,
	listMasterVersions,
	listRecallRules,
	listRoles,
	listTemplates,
	saveCompany,
	saveMasterVersion,
	saveRecallRule,
	saveTemplate,
	updateBranch,
} from "./procedures/admin";
import {
	registerEntry as allopathyRegisterEntry,
	listSoap,
	logChronic,
	recordImmunization,
	saveExam as saveAllopathyExam,
	saveSoap,
	triageEntry,
} from "./procedures/allopathy";
import {
	book as bookAppointment,
	bookVideo as bookVideoAppointment,
	callNext as callNextToken,
	cancel as cancelAppointment,
	captureConsent as captureVideoConsent,
	checkin as checkinAppointment,
	computeSlots,
	get as getAppointment,
	issueCertificate,
	issueRecall,
	list as listAppointments,
	queueBoard,
	reschedule as rescheduleAppointment,
	walkinToken,
} from "./procedures/appointments";
import { getSession } from "./procedures/auth";
import {
	bookNadi,
	createYogaBatch,
	dualCode as dualCodeAyush,
	enrollYoga,
	issueDiet,
	pauseExtendPackage as pauseExtendAyushPackage,
	recordSitting as recordAyushSitting,
	repertorize,
	saveCaseSheet,
	scheduleTherapy,
	sellPackage as sellAyushPackage,
} from "./procedures/ayush";
import {
	applyDiscount as applyBillingDiscount,
	cndnIssue as billingCndnIssue,
	collect as collectBilling,
	duesAging,
	getInvoice,
	gstExport,
	interimTab,
	invoiceFinalize,
	invoiceRaise,
	packageExpireRun,
	packageRedeem,
	packageSell,
	pricelistUpsert,
	repriceOnPayerSwitch,
	settleAdvance,
	settle as settleBilling,
} from "./procedures/billing";
import {
	bookChair,
	buildPlan as buildDentalPlan,
	chart as chartDental,
	closeStage as closeDentalStage,
	consent as dentalConsent,
	quote as dentalQuote,
	raiseLabJob,
	trackLabJob,
} from "./procedures/dental";
import {
	authorize as authorizeLab,
	cancelOrder as cancelDiagnosticOrder,
	collectSample,
	criticalAck,
	deliver as deliverLab,
	queue as diagnosticsQueue,
	getOrder as getDiagnosticOrder,
	orderLabs,
	panelCreate,
	qcLog,
	radioAuthorize,
	radioBook,
	radioCheckin,
	radioReportAttach,
	radioReschedule,
	receiveSample,
	resultEnter,
	testMasterUpsert,
} from "./procedures/diagnostics";
import {
	addendum as addEncounterAddendum,
	addDiagnosis as addEncounterDiagnosis,
	create as createEncounter,
	get as getEncounter,
	placeOrder as placeEncounterOrder,
	prescribe as prescribeEncounter,
	recordVitals as recordEncounterVitals,
	refill as refillEncounter,
	setFollowUp as setEncounterFollowUp,
	sign as signEncounter,
} from "./procedures/encounters";
import {
	addBlock as addFacilityBlock,
	create as createFacility,
	overlap as facilityOverlap,
	statusBoard as facilityStatusBoard,
	get as getFacility,
	list as listFacilities,
	logSterilization,
	occupy as occupyFacility,
	release as releaseFacility,
	setSchedule as setFacilitySchedule,
	update as updateFacility,
} from "./procedures/facilities";
import {
	drugAdminister as administerNursingDrug,
	ioChart as chartNursingIo,
	vitalsChart as chartNursingVitals,
	handoverCompile as compileNursingHandover,
	missedEscalate as escalateNursingMissed,
	board as nursingBoard,
	checklistRecord as recordNursingChecklist,
	painScore as scoreNursingPain,
	riskScreen as screenNursingRisk,
	handoverSign as signNursingHandover,
	sittingsSupport as supportNursingSitting,
	triageTag as tagNursingTriage,
	tasksFromOrders as tasksFromNursingOrders,
} from "./procedures/nursing";
import {
	attendanceMark,
	auditQuery,
	branchesCreate,
	complianceEvidence,
	explorerExportCsv,
	explorerGrant,
	explorerQuery,
	hrStaffUpsert,
	leaveDecide,
	leaveRequest,
	mastersUpsert,
	messagingOptOut,
	messagingRetry,
	messagingSend,
	payrollExport,
	reportsDefine,
	reportsRun,
	rosterPlan,
	seedPresets,
} from "./procedures/operations";
import {
	getCurrentOrganization,
	getOrganizationBySubdomain,
	listMyOrganizations,
	listOrganizations,
	updateCurrentOrganization,
} from "./procedures/organizations";
import {
	addAllergy,
	approveMerge,
	archiveConsent,
	dedupeCheck,
	enrolRecall,
	get as getPatient,
	linkFamily,
	list as listPatients,
	logCommunication,
	timeline as patientTimeline,
	register as registerPatient,
	requestMerge,
	setFlag,
	shareSlip,
} from "./procedures/patients";
import {
	transferAccept as acceptStockTransfer,
	batchReceive,
	getSale,
	grnVerify,
	itemUpsert,
	partialClose as partialCloseSale,
	cndnIssue as pharmacyCndnIssue,
	piBook,
	poCreate,
	reorderSuggest,
	returnAgainstBill,
	saleFromRx,
	transfer as transferStock,
} from "./procedures/pharmacy";
import {
	addEducation,
	addPosting,
	addRegistration,
	blockLeave,
	create as createPractitioner,
	deactivate as deactivatePractitioner,
	get as getPractitioner,
	list as listPractitioners,
	nextFreeSlot,
	conflict as practitionerConflict,
	setFee,
	setSchedule as setPractitionerSchedule,
	update as updatePractitioner,
} from "./procedures/practitioners";
import {
	alertSenior as alertPsychSenior,
	assess as assessPsych,
	bookCounselling,
	bookTele as bookPsychTele,
	caregiverConsent,
	chartWithdrawal,
	involuntaryHook,
	prescribeControlled,
	breakGlass as psychBreakGlass,
	recallList as psychRecallList,
	relapsePlan,
	saveSafetyPlan,
	scoreScale as scorePsychScale,
	screenRisk as screenPsychRisk,
	sideEffectCheck,
} from "./procedures/psych";
import {
	addendumAppend as appendRecordAddendum,
	registersAppend as appendRecordRegister,
	docsAttach as attachRecordDocs,
	retentionCheck as checkRecordRetention,
	registersExport as exportRecordRegisters,
	consentsGet as getRecordConsents,
	encounterGet as getRecordEncounter,
	dischargeIssue as issueRecordDischarge,
	notesMask as maskRecordNotes,
	merge as mergeRecords,
	dischargePending as pendingRecordDischarges,
	breakglass as recordsBreakglass,
	familySummary as recordsFamilySummary,
	timeline as recordsTimeline,
	search as searchRecords,
	sharePrint as shareRecordPrint,
	shareWhatsapp as shareRecordWhatsapp,
	docsVerify as verifyRecordDocs,
	registersVoid as voidRecordRegister,
} from "./procedures/records";
import {
	assess as assessRehab,
	bookSitting as bookRehabSitting,
	buildPackage as buildRehabPackage,
	discharge as dischargeRehab,
	exerciseSheet,
	openEpisode as openRehabEpisode,
	recordSitting as recordRehabSitting,
	dayBoard as rehabDayBoard,
	rescore as rescoreRehab,
	setGoals as setRehabGoals,
} from "./procedures/rehab";
import {
	admit as admitResident,
	allocateBed as allocateResidentBed,
	visitLog as appendResidentVisitLog,
	compileStayBill,
	getResident,
	listResidents,
	logDaily as logResidentDaily,
	polypharmacyReview,
	familySummary as residentFamilySummary,
	round as residentRound,
	scoreGeriatric,
} from "./procedures/residents";
import {
	createServiceProvider,
	listServiceProviders,
} from "./procedures/service-providers";
import {
	addDiscountRule,
	create as createService,
	definePackage,
	get as getService,
	list as listServices,
	mapFacilities as mapServiceFacilities,
	publish as publishService,
	redeem as redeemPackage,
	retire as retireService,
	setPrice as setServicePrice,
	update as updateService,
} from "./procedures/services";
import { listTenants, onboardTenant } from "./procedures/tenants";
import {
	createUser,
	getUser,
	listUsers,
	removeUser,
	updateUser,
} from "./procedures/users";

export const router = {
	admin: {
		createBranch,
		createRole,
		deleteRole,
		deleteTemplate,
		disableUser,
		getCompany,
		listBranches,
		listMasterVersions,
		listRecallRules,
		listRoles,
		listTemplates,
		logs: adminLogs,
		saveCompany,
		saveMasterVersion,
		saveRecallRule,
		saveTemplate,
		updateBranch,
	},
	allopathy: {
		listSoap,
		logChronic,
		recordImmunization,
		registerEntry: allopathyRegisterEntry,
		saveExam: saveAllopathyExam,
		saveSoap,
		triageEntry,
	},
	appointments: {
		book: bookAppointment,
		bookVideo: bookVideoAppointment,
		callNext: callNextToken,
		cancel: cancelAppointment,
		captureConsent: captureVideoConsent,
		checkin: checkinAppointment,
		computeSlots,
		get: getAppointment,
		issueCertificate,
		issueRecall,
		list: listAppointments,
		queueBoard,
		reschedule: rescheduleAppointment,
		walkinToken,
	},
	auth: {
		getSession,
	},
	ayush: {
		bookNadi,
		createYogaBatch,
		dualCode: dualCodeAyush,
		enrollYoga,
		issueDiet,
		pauseExtendPackage: pauseExtendAyushPackage,
		recordSitting: recordAyushSitting,
		repertorize,
		saveCaseSheet,
		scheduleTherapy,
		sellPackage: sellAyushPackage,
	},
	billing: {
		applyDiscount: applyBillingDiscount,
		cndnIssue: billingCndnIssue,
		collect: collectBilling,
		duesAging,
		getInvoice,
		gstExport,
		interimTab,
		invoiceFinalize,
		invoiceRaise,
		packageExpireRun,
		packageRedeem,
		packageSell,
		pricelistUpsert,
		repriceOnPayerSwitch,
		settle: settleBilling,
		settleAdvance,
	},
	dental: {
		bookChair,
		buildPlan: buildDentalPlan,
		chart: chartDental,
		closeStage: closeDentalStage,
		consent: dentalConsent,
		quote: dentalQuote,
		raiseLabJob,
		trackLabJob,
	},
	diagnostics: {
		authorize: authorizeLab,
		cancelOrder: cancelDiagnosticOrder,
		collectSample,
		criticalAck,
		deliver: deliverLab,
		getOrder: getDiagnosticOrder,
		orderLabs,
		panelCreate,
		qcLog,
		queue: diagnosticsQueue,
		radioAuthorize,
		radioBook,
		radioCheckin,
		radioReportAttach,
		radioReschedule,
		receiveSample,
		resultEnter,
		testMasterUpsert,
	},
	encounters: {
		addDiagnosis: addEncounterDiagnosis,
		addendum: addEncounterAddendum,
		create: createEncounter,
		get: getEncounter,
		placeOrder: placeEncounterOrder,
		prescribe: prescribeEncounter,
		recordVitals: recordEncounterVitals,
		refill: refillEncounter,
		setFollowUp: setEncounterFollowUp,
		sign: signEncounter,
	},
	facilities: {
		addBlock: addFacilityBlock,
		create: createFacility,
		get: getFacility,
		list: listFacilities,
		logSterilization,
		occupy: occupyFacility,
		overlap: facilityOverlap,
		release: releaseFacility,
		setSchedule: setFacilitySchedule,
		statusBoard: facilityStatusBoard,
		update: updateFacility,
	},
	nursing: {
		board: nursingBoard,
		checklistRecord: recordNursingChecklist,
		drugAdminister: administerNursingDrug,
		handoverCompile: compileNursingHandover,
		handoverSign: signNursingHandover,
		ioChart: chartNursingIo,
		missedEscalate: escalateNursingMissed,
		painScore: scoreNursingPain,
		riskScreen: screenNursingRisk,
		sittingsSupport: supportNursingSitting,
		tasksFromOrders: tasksFromNursingOrders,
		triageTag: tagNursingTriage,
		vitalsChart: chartNursingVitals,
	},
	operations: {
		attendanceMark,
		auditQuery,
		branchesCreate,
		complianceEvidence,
		explorerExportCsv,
		explorerGrant,
		explorerQuery,
		hrStaffUpsert,
		leaveDecide,
		leaveRequest,
		mastersUpsert,
		messagingOptOut,
		messagingRetry,
		messagingSend,
		payrollExport,
		reportsDefine,
		reportsRun,
		rosterPlan,
		seedPresets,
	},
	organizations: {
		bySubdomain: getOrganizationBySubdomain,
		current: getCurrentOrganization,
		list: listOrganizations,
		listMine: listMyOrganizations,
		update: updateCurrentOrganization,
	},
	patients: {
		addAllergy,
		approveMerge,
		archiveConsent,
		dedupeCheck,
		enrolRecall,
		get: getPatient,
		linkFamily,
		list: listPatients,
		logCommunication,
		register: registerPatient,
		requestMerge,
		setFlag,
		shareSlip,
		timeline: patientTimeline,
	},
	pharmacy: {
		batchReceive,
		cndnIssue: pharmacyCndnIssue,
		getSale,
		grnVerify,
		itemUpsert,
		partialClose: partialCloseSale,
		piBook,
		poCreate,
		reorderSuggest,
		returnAgainstBill,
		saleFromRx,
		transfer: transferStock,
		transferAccept: acceptStockTransfer,
	},
	practitioners: {
		addEducation,
		addPosting,
		addRegistration,
		blockLeave,
		conflict: practitionerConflict,
		create: createPractitioner,
		deactivate: deactivatePractitioner,
		get: getPractitioner,
		list: listPractitioners,
		nextFreeSlot,
		setFee,
		setSchedule: setPractitionerSchedule,
		update: updatePractitioner,
	},
	psych: {
		alertSenior: alertPsychSenior,
		assess: assessPsych,
		bookCounselling,
		bookTele: bookPsychTele,
		breakGlass: psychBreakGlass,
		caregiverConsent,
		chartWithdrawal,
		involuntaryHook,
		prescribeControlled,
		recallList: psychRecallList,
		relapsePlan,
		saveSafetyPlan,
		scoreScale: scorePsychScale,
		screenRisk: screenPsychRisk,
		sideEffectCheck,
	},
	records: {
		addendumAppend: appendRecordAddendum,
		breakglass: recordsBreakglass,
		consentsGet: getRecordConsents,
		dischargeIssue: issueRecordDischarge,
		dischargePending: pendingRecordDischarges,
		docsAttach: attachRecordDocs,
		docsVerify: verifyRecordDocs,
		encounterGet: getRecordEncounter,
		familySummary: recordsFamilySummary,
		merge: mergeRecords,
		notesMask: maskRecordNotes,
		registersAppend: appendRecordRegister,
		registersExport: exportRecordRegisters,
		registersVoid: voidRecordRegister,
		retentionCheck: checkRecordRetention,
		search: searchRecords,
		sharePrint: shareRecordPrint,
		shareWhatsapp: shareRecordWhatsapp,
		timeline: recordsTimeline,
	},
	rehab: {
		assess: assessRehab,
		bookSitting: bookRehabSitting,
		buildPackage: buildRehabPackage,
		dayBoard: rehabDayBoard,
		discharge: dischargeRehab,
		exerciseSheet,
		openEpisode: openRehabEpisode,
		recordSitting: recordRehabSitting,
		rescore: rescoreRehab,
		setGoals: setRehabGoals,
	},
	residents: {
		admit: admitResident,
		allocateBed: allocateResidentBed,
		compileStayBill,
		familySummary: residentFamilySummary,
		getResident,
		listResidents,
		logDaily: logResidentDaily,
		polypharmacyReview,
		round: residentRound,
		scoreGeriatric,
		visitLog: appendResidentVisitLog,
	},
	serviceProviders: {
		create: createServiceProvider,
		list: listServiceProviders,
	},
	services: {
		addDiscountRule,
		create: createService,
		definePackage,
		get: getService,
		list: listServices,
		mapFacilities: mapServiceFacilities,
		publish: publishService,
		redeem: redeemPackage,
		retire: retireService,
		setPrice: setServicePrice,
		update: updateService,
	},
	tenants: {
		list: listTenants,
		onboard: onboardTenant,
	},
	users: {
		create: createUser,
		get: getUser,
		list: listUsers,
		remove: removeUser,
		update: updateUser,
	},
};
