import { createAccessControl } from "@aspen-os/framework/client";

export const access_control = createAccessControl({
	audit_logs: ["read"],
	client_contracts: ["create", "read", "update", "archive"],
	clients: ["create", "read", "update", "archive"],
	drafts: ["create", "read", "update", "delete"],
	filter_views: ["create", "read", "update", "delete"],
	job_mandates: [
		"create",
		"read",
		"update",
		"archive",
		"assign",
		"link_prospect",
		"verify",
	],
	notification: ["read", "update", "archive"],
	prospects: ["create", "read", "update", "archive"],
	reminders: ["create", "read", "archive"],
	tasks: ["create", "read", "update", "archive", "assign"],
	team_members: ["create", "read", "update", "archive", "manage-roles"],
});

export const roles = {
	admin: access_control.newRole({
		audit_logs: ["read"],
		client_contracts: ["create", "read", "update", "archive"],
		clients: ["create", "read", "update", "archive"],
		drafts: ["create", "read", "update", "delete"],
		filter_views: ["create", "read", "update", "delete"],
		job_mandates: [
			"create",
			"read",
			"update",
			"archive",
			"assign",
			"link_prospect",
			"verify",
		],
		notification: ["read", "update", "archive"],
		prospects: ["create", "read", "update", "archive"],
		reminders: ["create", "read", "archive"],
		tasks: ["create", "read", "update", "archive", "assign"],
		team_members: ["create", "read", "update", "archive", "manage-roles"],
	}),
	receptionist: access_control.newRole({
		client_contracts: ["create", "read", "update", "archive"],
		clients: ["create", "read", "update", "archive"],
		drafts: ["create", "read", "update", "delete"],
		filter_views: ["create", "read", "update", "delete"],
		job_mandates: ["create", "read", "update", "archive", "assign"],
		notification: ["read", "update", "archive"],
		prospects: ["create", "read"],
		reminders: ["create", "read", "archive"],
		tasks: ["create", "read", "update", "archive", "assign"],
		team_members: ["read"],
	}),
	doctor: access_control.newRole({
		drafts: ["create", "read", "update", "delete"],
		filter_views: ["create", "read", "update", "delete"],
		job_mandates: ["read"],
		notification: ["read", "update", "archive"],
		prospects: ["create", "read", "update"],
		reminders: ["create", "read", "archive"],
		tasks: ["create", "read", "update", "archive", "assign"],
		team_members: ["read"],
	}),
} as const;
